name: Web Build

on:
  push:
    branches: [ main, master ]
    paths:
      - 'web/**'
      - '.github/workflows/web-build.yml'
  pull_request:
    paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # Ensure deterministic build-time envs
          NEXT_PUBLIC_API_BASE: '/api'
        run: npm run build

      - name: Lint
        run: npm run lint -- --no-error-on-unmatched-pattern

